### ISSUE TITLE
frida installing on windows

### ISSUE THREAD

**Issue by navidevangel** [frida/frida-website#174]
hey
i installed last version of python
but command of installing is invalid

`
C:\Users\USERl>pip install frida
    'pip' is not recognized as an internal or external command,
   operable program or batch file.
`

**Comment by manishsahani999** [comment]
The problem seems that your pip is not installed correctly, try checking the pip version for ensuring it's working.

If you are still unable to use pip, you can use a super-easy way to install by running get-pip script (read about the installation here - https://pip.pypa.io/en/stable/installing/).

steps to install pip - 
1. `curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py`
2. `python get-pip.py`


then run `pip --version` to verify the installation.
